name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUM_OF_LAPS: ${{ secrets.NUM_OF_LAPS }}
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn
    - run: yarn test

